---
# This playbook configures the firewall based on stateful packet filtering.

- name: configure iptables packet filtering
  template: src=iptables.rules.j2 dest=/etc/iptables/iptables.rules
    owner=root group=root mode=0644
  notify: restore the iptables rules

- name: ensure the iptables rules are restored on boot
  service: name=iptables state=started enabled=true

- name: configure ip6tables packet filtering
  template: src=ip6tables.rules.j2 dest=/etc/iptables/ip6tables.rules
    owner=root group=root mode=0644
  notify: restore the ip6tables rules

- name: ensure the ip6tables rules are restored on boot
  service: name=ip6tables state=started enabled=true
